services:
  backend:
    image: ${IMAGE_ID}:latest
    container_name: backend-app
    ports:
      - "8080:8080"
    env_file: .env
    restart: on-failure:3
  db:
    image: postgres:17.4
    container_name: database-postgres
    restart: always
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    env_file: .env
    ports: 
      - "5430:5432"
