name: CI - Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: false
        type: string
        default: ${{vars.IMAGE_ID}}

permissions:
  contents: read
  packages: write

jobs:
  continuos_integration:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'DEV' || 'PROD' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build Docker image
        run: |
          VERSION=sha-${GITHUB_SHA::7}
          docker build -t ${{vars.IMAGE_ID}}:latest -t ${{vars.IMAGE_ID}}:$VERSION .

      - name: Push Docker image
        run: |
          docker push ${{vars.IMAGE_ID}}:latest
          docker push ${{vars.IMAGE_ID}}:sha-${GITHUB_SHA::7}
          
          
      
